sudo: false
dist: trusty
language: node_js
node_js:
- lts/*
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: xy4GgyYK0pomLoNqUZdmkGKMIRuRIm5V4jkLXtGdQStxNj2jR2XD5wCx6PKxmA+qYSeiOwmwFfYGhXD1b0ih98LxcVnlpDEDI2hCX70688rorAXUTMkpSCgpXEmSE2UordGL6HLKHcxpcAu/Dw2b+rplVreWqF6UhLgNal2a4ZHxOkvjlvr9rrgubFMyhpxYLLQyTxerIx3vn7761GbDJdAFTrdiMT7AIyJ1/H5lNuRKw9tD45TBz+xSku1yGcImZ8puTHs1PKgHk23Q6XmuemvVXZs1PG3GR/4c7zbJVv1JGFpp0BedC5rfIOqHIk5W6qqz8WPmZRURfrR/NkfjATZNLYYwQnVdAx0l5LrjsZ1jYijZ0ODe6Vw0I/VNJ2E390IYWsAd5t3/FjHrHOfYbH6pA7oYG7BuOKwCAHldD9X7HxAgxhx53S1QKHHeNGjSPazeA4eLSGWqGTPpSD+nJgLBiw7+4SyvvMFM2quhfb4XWIXIw/Bfdo+PoVKmoqUge1Hv6+Hk999uLXDFweQby1MjyYhW4SeWs/I8F92yIyCQ4juWaimgdAKlOuA4+QSkVbFMCvTi1iPpkMHghxzRh4a0a/2IQgtrkT5GSdSgrjU82hstAtatO5KMRZ4I4vYcnliubkdUSqG06q/mfXrO5DEU4XShhpxDRn19O00yR1g=
  - secure: Ge9myqDkOgsoXdYTsS19zztYOoI4Q2g+2VFiJrl/hfAxan3VWaRs92UH0s4pTPSDt0aBbD0eAzecdtDXrCtFUat1QffAjDvpcQNH8Pg1zPuWF8yOgOZ4b8VsuARxM/mET2cOKK0sVTwe8MP7UckPpiitP1ubLfapXgheosDtzFWT7OQQqrZ4Kc6nHFsZlulzlq5mJ5i3jFXoMxlHq5Dvpqtk6kNZiTuVsw09JymuqYjFe0VKXMtcC665zYXJ8SIiQ2VmOtChf00wpcZSnIwiJS6sujGugcun0xs6adOYMCvJe0VhUt44oXAxof7lBAX8a3Fz2m9bC5uN4+OIyh8FTfhLXQVAHPgiIkYmYyaCy7rnxjOUe6iAPL6AeEf0oNqf+eg2KfwXj+7j/EDLNakXMpjj68D1rliF+k8APgsaetgucEFwSw9AqzU5LD4ZDkUtPeB9pnDcmNKg3Upkinlb18NXxNyTDw3d7C2+HRoKVyVI04IUpE1+U2yABoGKR9DafNoXiTq+lyw3J8W2y7c+GGmIi6Bh+/I7lnbrLEOR9vtnMjaGgPPHqpA5brRqQZdks3ONXBP4KZqBRYPjv4P5dtdRJUNnOgdPOO+F60o8CFAkk87GhwW4MBBCPA7afZC1pAPskUDKyj/fCMel1BZUC0XhunyQgLejhnVdPRwrfmY=
  - secure: e5lmYZuR09Hl99Z955oNkrs9ROgmjo4fodkJUazzkkLWN4DJVlHiRePW0fytzpsJsuQZzr8Wv+GMRHuEf+HMhRRJZ+h+a+y6iY9H585gZzRs/QrovmP9V0ItX+rg1KURgWZoxU8V0YnpUIT0n3FiWyZZmPuCPw+BLRHBFVb7MxWe8V2Ot4JRfTvpzVmYzYPVDz67SQeZShtuKBCMt39mjkr+CM0BOp6P6psFQMykhY4rjast8aO1uuhaiF9SI4C4UKaA+2TuaOaf+9T5g/9M56/2dMH7UxCa7mPVXUUSnk5HWmYUlSgNjb1pNcsMq+za3SboMiEYkBRWIrka+Al2zzOvOImwTbUiORj4HY3Xbfojy3CTRyd8KbmW1iqOHBhTOPkId33LDmmPaNu1ESl9w1OBaLsgX2uRQA/we8aAUvv12tW42FYliX5sXARBDpSvSzrzAdgcZeZfxqklDu7g3QrBFHvIhw91B8Zh47warcsIRfvLUdJ7zRLyuxI7SA4u1x0kv6ajWnD6Hxk8Sp+NtqaoS8Cza84XPYsvWbyMkdQFKP82HZR3z8kpchw7+sz1jIXVSWabisyi+KmcznLSmaa0f/xIMaVJQQwUfOFbv3L0I1MWg7kBw+XAx+EJ4dsuXRhd8HgJvBqiKNosge5QVzhtePJL3j50sT6mHJESSEU=
  - secure: p9DyLFcPrBqe/4dfoBJIz5MWJ7S8wxsQbdXShEYl6rg1t0zbhiADOTdOxmyHNcLGH7a6ZmoYHBdWnszplceuiZoD21+Rp7INmeBuF/OMEUGjSZRYrD/ZkOGd/rzJW/y2tkidUwWkRX0zLFhsJCuSDQ3s6EEdqrbAHYQ3L58b25AUNupbN7vNTP91WPCnIkAtcNI69mZpFtow1xCc3jHyKM3E5g3gLX9RNR+xnWW4wgcT89Kb2w+gqXl+gdeQ7toygK1YTe/1tb8MPSHU2DeVrRJpqyQWxXdTKT18NKTCCCyi5zWyLq9hntxERYLltEuTcudNfZsKVAPrfCpoZx7jdfuvNcqOKGSa+0P0vqKtoMkSOoeBA4+mYamLAa6IV52B2kH/FgsiSbinmzyrgssxVyGO1VoZj3wGj4cuPCLkSGdFC9eRTVmMlO7jxC8JRmJiTpegdtw/LAzpw1W7389nIqGSgZ+cz9/mkM7C6d7xlZgj9j9PX1I5/BzLyupWTEMyeRQcRNP0G8bWpKmwzvTZRXjBTvJs2NkROX4Qq+Rvlla836Ufjl6hYXu9WcmkaPcy9ltR1bygNnpQaslARJru2fMPT7NX/WpHElLA1OnBk/LKLd6/LsiO+nEr7aVVmZ0sScA7b0X84t4RFbObhLoefPQ9p9H/Y8r4DHni3xxJRMY=
